### ISSUE TITLE
Add a new enqueueMixin overload?

### ISSUE THREAD

**Issue by KameiB** [fonnymunkey/FermiumBooter#2]
Can you add an overload to the following method:
`FermiumRegistryAPI.enqueueMixin`
so it accepts a `String modId`, and only apply the mixin if its corresponding mod (the modId in this argument) is in the loading list?

Mixin devs can then call `FermiumRegistryAPI.enqueueMixin` and pass the modId as an argument, to indicate that the current mixin depends on that mod.
Example: `FermiumRegistryAPI.enqueueMixin(true, myMixin.getJson(), myMixin.getModId());`

This would be a nice extra security layer for players that want to enable all mixins but don't want error spam in the latest.log if the corresponding mod doesn't exist in the current instance.

You can get the mod id here:
https://github.com/fonnymunkey/FermiumBooter/blob/fb880a6da43c6ce5d3856d106e5931d7dba460dc/src/main/java/fermiumbooter/mixin/FermiumMixinLoader.java#L45
and add `mod.getModId()` to a List, then use it where it's needed.

I understand this could conflict with the current overload:
https://github.com/fonnymunkey/FermiumBooter/blob/fb880a6da43c6ce5d3856d106e5931d7dba460dc/src/main/java/fermiumbooter/FermiumRegistryAPI.java#L29

But just consider it, please?

**Comment by fonnymunkey** [comment]
By the time;
https://github.com/fonnymunkey/FermiumBooter/blob/main/src/main/java/fermiumbooter/mixin/FermiumMixinLoader.java#L45
is reached, the Loader has already populated the namedMods list, and FermiumBooter creating its own list would be redundant.
You can provide a Supplier of `() -> Loader.isModLoaded(modid)` when enqueuing late loaded mixins to have them only be enabled if the relevant modid is present.

**Comment by KameiB** [comment]
Ooh I wasn't aware of the timings!
I applied your response and it solved my problem.
Thanks!
